variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  PARAMETERS: "--show-version --errors --batch-mode --fail-at-end -Dversions.skip=true -P foss-parent-verification"

.validate: &validate
  stage: build
  script:
    - 'mvn $PARAMETERS test-compile'
  except:
    - gh-pages

.test: &test
  stage: test
  script:
    - 'mvn $PARAMETERS verify site site:stage'
  except:
    - gh-pages
  
before_script:
  - id

validate:jdk7:
  <<: *validate
  image: maven:3.3.9-jdk-7

validate:jdk8:
  <<: *validate
  image: maven:3.3.9-jdk-8

test:jdk7:
  <<: *test
  image: maven:3.3.9-jdk-7

test:jdk8:
  <<: *test
  image: maven:3.3.9-jdk-8
  artifacts:
    paths:
      - target/staging/tljunit-parent/

pages:
  stage: deploy
  script:
    - mv target/staging/tljunit-parent/ public
  dependencies:
    - test:jdk8
  artifacts:
    paths:
    - public
  only:
    - master

